services:
  gdoc_srv:
    build: .
    container_name: web
    volumes:
      - ../data/store.db:/app/store.db:ro
    restart: always

  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared
    command: tunnel --no-autoupdate run
    environment:
      TUNNEL_TOKEN_FILE: /run/secrets/cloudflared_token
    restart: always
    secrets:
      - cloudflared_token
secrets:
  cloudflared_token:
    file: .tunnel_token